### ISSUE TITLE
Add system properties 

### ISSUE THREAD

**Issue by senithdesilva** [Azure-Samples/IoTMQTTSample#2]
How to do I make sure the contentType is set as application/JSON and contentEncoding is set as UTF-8, UTF-16, or UTF-32 in the system properties when publishing a message to IoTHub?

I'm using the same library, and I'm trying to perform message routing at the IoTHub end. But the query doesn't work, I think IoTHub isn't evaluating the query expression on message body.

**Comment by ericmitt** [comment]
Sorry to be so late on this. Are you on Linux? Do you use VSCode? On which sample are you working

**Comment by senithdesilva** [comment]
@ericmitt Thats alright. Im using the following solution  /src/Shared/MQTT_Mosquitto.cpp. Yes I am developing this in Linux and using VSCode.

**Comment by ryanwinter** [comment]
Closing for now, please feel free to reopen if needed.
