### ISSUE TITLE
Issues connecting to wlan and sending MQTT packets

### ISSUE THREAD

**Issue by skuppens** [Azure-Samples/IoTMQTTSample#4]
Hi, 

I'm having trouble implementing the project for micropython.
Trying to get my pycom device to connect to my home wifi and to upload some values to Azure IoT hub.

My issues:

1.  I can't seem to get connected using your boot.py code.
The error I receive is this:
 `  File "boot.py", line 39, in <module>
AttributeError: 'module' object has no attribute 'STA_IF'`

If I use another solution it gets connected. using this: [https://forum.pycom.io/topic/104/boot-py-wifi-script/2](url)

2. second problem is this:
`Traceback (most recent call last):
  File "main.py", line 38, in <module>
  File "umqtt/robust.py", line 27, in reconnect
  File "umqtt/robust.py", line 23, in reconnect
  File "umqtt/simple.py", line 57, in connect
TypeError: can't convert 'NoneType' object to str implicitly`

I tried version 2 of the robust en simple mqtt modules but they had the same error.
Any ideas?

Thank you for your help.
Kindest regards,

**Comment by ryanwinter** [comment]
MicroPython samples has been removed.
