### ISSUE TITLE
Can Mosquitto connect to MQTT over Websocket for Azure IoT?

### ISSUE THREAD

**Issue by sirsendu** [Azure-Samples/IoTMQTTSample#9]
Hi,

I had implemented one solution based on the sample where I used Port 8883. All works perfect.
But now I am facing issue over firewall since 8883 is blocked there. Thus need to use MQTT over Websocket.
Thus was looking for solution using mosquitto itself. Is there any way, can anyone point me to that?

I found documents and sample on websocket, but all of them are localhost broker. It can be great if I can get some sample or points by which I can make communicate Azure IoT using 443 port.

**Comment by ryanwinter** [comment]
Hi @sirsendu,

IoT Hub supports Websocket over port 443. Simply connect to port 443 using the mosquitto library.
https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-protocols

FYI: Mosquitto_pub does not support Websockets.
